name: Build ReJavadoc

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Protoc
      uses: arduino/setup-protoc@v3
    - name: Build Project
      run: make build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup Protoc
      uses: arduino/setup-protoc@v3
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Build Documentation
      run: make -B docs
    - name: Deploy Documentation
      run: bash doc.sh ${GITHUB_SHA::7}